version: "3"

services:
          rabbit:
                  hostname: rabbit
                  image: rabbitmq:latest
                  ports:
                        - "5672:5672"
                  volumes:
                        - .:/app
          web:
                  env_file:
                        - env_file
                  build: .
                  ports:
                        - "5000:5000"
                  restart: on-failure
                  links:
                        - rabbit

