version: "3"

services:
          rabbit:
                  hostname: rabbit
                  image: rabbitmq:management
                  environment:
                        - RABBITMQ_DEFAULT_USER=user
                        - RABBITMQ_DEFAULT_PASS=user
                  ports:
                        - "5672:5672"
                        - "15672:15672"
                  volumes:
                        - .:/app
          web:
                  env_file:
                        - env_file
                  build: .
                  ports:
                        - "5000:5000"
                  restart: on-failure
                  links:
                        - rabbit

